[http]
    port=":8080"
    read_timeout=60
    write_timeout=60

[database]
    host="10.0.10.209"
    port=5432
    dbname="smb"
    user="ytf"
    password="ytf@2021"
    sslmode="disable"

[redis]
    host="10.0.10.209:6379"
    password="ytf@2021"
    db=5
    max_idle=10
    max_active=10

[rocketmq]
    server = [
    "127.0.0.1:9876"
     ]